#For older docker compose versions the following line is required
#version: '3.8'
services:
  eureka-server:
    image: hurban/discovery-service:latest
    environment:
      JAVA_TOOL_OPTIONS: "-XX:-UseContainerSupport"
      #OpenTelemetry Config. Remove or change OTEL_SDK_DISABLED to false.
      OTEL_SDK_DISABLED: true
      OTEL_TRACES_SAMPLER: always_on
      OTEL_TRACES_EXPORTER: otlp
      OTEL_METRICS_EXPORTER: otlp
      OTEL_LOGS_EXPORTER: otlp
      OTEL_EXPORTER_OTLP_PROTOCOL: grpc
      OTEL_SERVICE_NAME: eureka-server
      OTEL_EXPORTER_OTLP_ENDPOINT: http://opentelemetry-collector:4317
      OTEL_PROPAGATORS: tracecontext,baggage,
    networks:
      - app-network
    ports:
      - "8761:8761"
    healthcheck:
      test: timeout 10s bash -c ':> /dev/tcp/127.0.0.1/8761' || exit 1
      interval: 20s
      timeout: 10s
      retries: 5
  unique-uuid-api-1:
    image: hurban/unique-uuid-api:latest
    environment:
      EUREKA__INSTANCE__IPADDRESS: "unique-uuid-api-1"
      EUREKA__INSTANCE__PORT: 5273
    networks:
      - app-network
    depends_on:
      eureka-server:
        condition: service_healthy
    ports:
      - "8080:5273"
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 100M
        reservations:
          cpus: '0.01'
          memory: 50M
  unique-uuid-api-2:
    image: hurban/unique-uuid-api:latest
    environment:
      EUREKA__INSTANCE__IPADDRESS: "unique-uuid-api-2"
      EUREKA__INSTANCE__PORT: 5273
    networks:
      - app-network
    depends_on:
      eureka-server:
        condition: service_healthy
    ports:
      - "8081:5273"
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 100M
        reservations:
          cpus: '0.01'
          memory: 50M
  unique-uuid-api-3:
    image: hurban/unique-uuid-api:latest
    environment:
      EUREKA__INSTANCE__IPADDRESS: "unique-uuid-api-3"
      EUREKA__INSTANCE__PORT: 5273
    networks:
      - app-network
    depends_on:
      eureka-server:
        condition: service_healthy
    ports:
      - "8082:5273"
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 100M
        reservations:
          cpus: '0.01'
          memory: 50M
  custom-load-balancer:
    image: hurban/custom-alb:latest
    environment:
      SPRING_PROFILES_ACTIVE: "docker"
      MEM_URI_PATH: "/api/MemoryStats/MemoryStatus"
      SESSION_COOKIE_NAME: "SERVICE_INSTANCE_ID"
      SESSION_COOKIE_DURATION_MINUTES: "1"
      INSTANCE_SERVICE_NAME: "unique-uuid-api"
      #OpenTelemetry Config. Remove or change OTEL_SDK_DISABLED to false.
      OTEL_SDK_DISABLED: true
      OTEL_TRACES_SAMPLER: always_on
      OTEL_TRACES_EXPORTER: otlp
      OTEL_METRICS_EXPORTER: otlp
      OTEL_LOGS_EXPORTER: otlp
      OTEL_EXPORTER_OTLP_PROTOCOL: grpc
      OTEL_SERVICE_NAME: custom-load-balancer
      OTEL_EXPORTER_OTLP_ENDPOINT: http://opentelemetry-collector:4317
      OTEL_PROPAGATORS: tracecontext,baggage,
    networks:
      - app-network
    depends_on:
      eureka-server:
        condition: service_healthy
      unique-uuid-api-1:
        condition: service_started
      unique-uuid-api-2:
        condition: service_started
      unique-uuid-api-3:
        condition: service_started    
    ports:
      - "8888:8888"

networks:
  app-network:
    driver: bridge