server:
  port: 8761
spring:
  application:
    name: discovery-service
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    expected-client-renewal-interval-seconds: 30